var data = [
  {
    id: 'bp-1',
    name: 'Osho',
    feature: 'Backpack',
    price: '$70',
    byprice: 'under-100',
    dimensions: 'L33cm x H40cm x W11cm',
    sex: 'bag-Women',
    brand: 'Kipling',
    brandvalue: 'brand-Kipling',
    manufacturer: 'Malaysia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Woven texture backpack; Polyester; Zip fastening; Lined interior; 1 exterior front zip pocket; 2 exterior side zip pockets; 1 interior zip pocket; Volume: 25L; Iconic monkey keychain; Single grab handle; Adjustable shoulder straps',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-kipling-grey-green-1.jpg',
    pic2: 'images_final/product/backpack-kipling-grey-green-2.jpg',
    pic3: 'images_final/product/backpack-kipling-grey-green-3.jpg',
    pic4: 'images_final/product/backpack-kipling-grey-green-4.jpg',
    pic5: 'images_final/product/backpack-kipling-grey-green-5.jpg',
    pic6: 'images_final/product/backpack-kipling-grey-green-6.jpg',
  },
  {
    id: 'bp-2',
    name: 'City Pack S',
    feature: 'Backpack',
    price: '$159',
    byprice: 'under-500',
    dimensions: 'L24cm x H28cm x W17cm',
    sex: 'bag-Women',
    brand: 'Kipling',
    brandvalue: 'brand-Kipling',
    manufacturer: 'Malaysia',
    material: 'Polyamide',
    materialvalue: 'mat-Polyamide',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Solid tone top flap mini backpack with embroidered brand patch; Polyamide; Lined interior; Magnetic and zip closure; 1 inner zip pocket; 1 inner slot pocket; 2 exterior zip pockets; 2 side magnetic pockets; Top grab handle; Adjustable shoulder straps; Comes with a metallic monkey keychain',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-kipling-black-1.jpg',
    pic2: 'images_final/product/backpack-kipling-black-2.jpg',
    pic3: 'images_final/product/backpack-kipling-black-3.jpg',
    pic4: 'images_final/product/backpack-kipling-black-4.jpg',
    pic5: 'images_final/product/backpack-kipling-black-5.jpg',
    pic6: 'images_final/product/backpack-kipling-black-6.jpg',
  },
  {
    id: 'bp-3',
    name: 'Seoul Urban Palm',
    feature: 'Backpack',
    price: '$250',
    byprice: 'under-500',
    dimensions: 'L35cm x H44cm x W20.5cm',
    sex: 'bag-Women',
    brand: 'Kipling',
    brandvalue: 'brand-Kipling',
    manufacturer: 'Malaysia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- All over printed laptop backpack; Polyester ; 1 main zipper compartment ; 2 outer zipper compartments ; 2 side bottle slots compartments ; 1 internal padded sleeve compartment ; 1 internal sleeve compartment ; Comes with monkey keychain ; 1 pouch pocket for wallet ; 2 pen loops ; 1 key fob ; Adjustable straps ; Lined interior<br>',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-kipling-palm-1.jpg',
    pic2: 'images_final/product/backpack-kipling-palm-2.jpg',
    pic3: 'images_final/product/backpack-kipling-palm-3.jpg',
    pic4: 'images_final/product/backpack-kipling-palm-4.jpg',
    pic5: 'images_final/product/backpack-kipling-palm-5.jpg',
    pic6: 'images_final/product/backpack-kipling-palm-6.jpg',
  },
  {
    id: 'bp-4',
    name: 'Expedition Montana',
    feature: 'Backpack',
    price: '$55',
    byprice: 'under-100',
    dimensions: 'L30.5cm x H46cm x W13.5cm',
    sex: 'bag-Men',
    brand: 'Superdry',
    brandvalue: 'brand-Superdry',
    manufacturer: 'Vietnam',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Solid tone 21L backpack with logo badge ; Polyester ; Zippered main compartment ; 1 front zip pocket ; 2 side pockets with snap closure ; 1 inner laptop sleeve ; 2 inner slip pockets ; Lined interior ; Grab handle ; Adjustable shoulder straps ; Padded back panel<br>',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-superdry-black-1.jpg',
    pic2: 'images_final/product/backpack-superdry-black-2.jpg',
    pic3: 'images_final/product/backpack-superdry-black-3.jpg',
    pic4: 'images_final/product/backpack-superdry-black-4.jpg',
    pic5: 'images_final/product/backpack-superdry-black-5.jpg',
    pic6: 'images_final/product/backpack-superdry-black-6.jpg',
  },
  {
    id: 'bp-5',
    name: 'Herschel Unisex',
    feature: 'Backpack',
    price: '$345',
    byprice: 'under-500',
    dimensions: 'L27cm x H40cm x W12.5cm',
    sex: 'bag-Men',
    brand: 'Herschel',
    brandvalue: 'brand-Herschel',
    manufacturer: 'United State',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      'An iconic silhouette with timeless appeal, the popular Herschel Little America backpack elevates a classic mountaineering style with modern functionality.; Signature striped fabric liner; Padded and fleece lined 15” laptop sleeve - Drawcord closure; Magnet fastened straps with metal pin buckles; Front pocket with hidden zipper and key clip; Internal media pocket with headphone port; Contoured shoulder straps and air mesh back padding; Classic woven',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-herschel-black-1.jpg',
    pic2: 'images_final/product/backpack-herschel-black-2.jpg',
    pic3: 'images_final/product/backpack-herschel-black-3.jpg',
    pic4: 'images_final/product/backpack-herschel-black-4.jpg',
  },
  {
    id: 'bp-6',
    name: 'Adidas Classic',
    feature: 'Backpack',
    price: '$170',
    byprice: 'under-500',
    dimensions: 'L38cm x H40cm x W15cm',
    sex: 'bag-Men',
    brand: 'Adidas',
    brandvalue: 'brand-Adidas',
    manufacturer: 'Indonesia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'White',
    colorvalue: 'color-White',
    description:
      '- Adidas performance ; Best for performance ; adidas three stripes backpack ; Recycled polyester ; Zip fastening ; 1 main compartment ; 1 front pocket ; 2 side slip pockets ; 1 inner laptop sleeve pocket ; Unlined interior ; Adjustable straps',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-adidas-white-1.jpg',
    pic2: 'images_final/product/backpack-adidas-white-2.jpg',
    pic3: 'images_final/product/backpack-adidas-white-3.jpg',
    pic4: 'images_final/product/backpack-adidas-white-4.jpg',
    pic5: 'images_final/product/backpack-adidas-white-5.jpg',
    pic6: 'images_final/product/backpack-adidas-white-6.jpg',
  },
  {
    id: 'bp-7',
    name: 'Adidas Classic Urban',
    feature: 'Backpack',
    price: '$75',
    byprice: 'under-100',
    dimensions: 'L28cm x H46cm x W16cm',
    sex: 'bag-Men',
    brand: 'Adidas',
    brandvalue: 'brand-Adidas',
    manufacturer: 'Indonesia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Adidas performance ; Best for training ; Colourblock backpack with brand label ; Recycled polyblend ; Lined interior ; Zip closure ; Front zip pocket ; Interior laptop divider<br> \n- Interior zip pocket ; 2 side slot pockets ; Top grab handle ; Adjustable shoulder straps<br>',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-adidas-black-1.jpg',
    pic2: 'images_final/product/backpack-adidas-black-2.jpg',
    pic3: 'images_final/product/backpack-adidas-black-3.jpg',
    pic4: 'images_final/product/backpack-adidas-black-4.jpg',
    pic5: 'images_final/product/backpack-adidas-black-5.jpg',
    pic6: 'images_final/product/backpack-adidas-black-6.jpg',
  },
  {
    id: 'bp-8',
    name: 'Brasilia 9.0 Printed',
    feature: 'Backpack',
    price: '$65',
    byprice: 'under-100',
    dimensions: 'L29cm x H46cm x W11cm',
    sex: 'bag-Women',
    brand: 'Nike',
    brandvalue: 'brand-Nike',
    manufacturer: 'Vietnam',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Best for training ; Camouflage print logo backpack \n- Polyester \n- Zip fastening \n- Lined interior \n- 1 exterior front velcro pocket \n- 2 exterior side mesh pockets \n- 2 main zip compartments \n- 1 interior zip mesh pocket \n- Adjustable shoulder straps',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-nike-grey-1.jpg',
    pic2: 'images_final/product/backpack-nike-grey-2.jpg',
    pic3: 'images_final/product/backpack-nike-grey-3.jpg',
    pic4: 'images_final/product/backpack-nike-grey-4.jpg',
    pic5: 'images_final/product/backpack-nike-grey-5.jpg',
    pic6: 'images_final/product/backpack-nike-grey-6.jpg',
  },
  {
    id: 'bp-9',
    name: 'UA Kazoku Sackpack',
    feature: 'Backpack',
    price: '$54',
    byprice: 'under-100',
    dimensions: 'L38cm x H52cm x W15cm',
    sex: 'bag-Men',
    brand: 'Under Armour',
    brandvalue: 'brand-UnderArmour',
    manufacturer: 'Indonesia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'White',
    colorvalue: 'color-White',
    description:
      '- Best for training; Camouflage print logo backpack; Polyester; Zip fastening; Lined interior; 1 exterior front velcro pocket; 2 exterior side mesh pockets; 2 main zip compartments; 1 interior zip mesh pocket; Adjustable shoulder straps',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-under-armour-white-1.jpg',
    pic2: 'images_final/product/backpack-under-armour-white-2.jpg',
    pic3: 'images_final/product/backpack-under-armour-white-3.jpg',
    pic4: 'images_final/product/backpack-under-armour-white-4.jpg',
    pic5: 'images_final/product/backpack-under-armour-white-5.jpg',
    pic6: 'images_final/product/backpack-under-armour-white-6.jpg',
  },
  {
    id: 'bp-10',
    name: 'Cross Training',
    feature: 'Backpack',
    price: '$65',
    byprice: 'under-100',
    dimensions: 'L30cm x H47cm x W15cm',
    sex: 'bag-Men',
    brand: '361°',
    brandvalue: 'brand-361°',
    manufacturer: 'China',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Red',
    colorvalue: 'color-Red',
    description:
      '- Best for training; Two-toned backpack with graphic print; Polyester; Front flap & zip compartments; Main compartment with zip closure; Lined interior; 1 inner mesh pocket, 1 non-padded sleeve; Top grab handle; Adjustable shoulder straps',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/backpack-361-black-1.jpg',
    pic2: 'images_final/product/backpack-361-black-2.jpg',
    pic3: 'images_final/product/backpack-361-black-3.jpg',
    pic4: 'images_final/product/backpack-361-black-4.jpg',
    pic5: 'images_final/product/backpack-361-black-5.jpg',
    pic6: 'images_final/product/backpack-361-black-6.jpg',
  },
  {
    id: 'hb-1',
    name: 'Michael Kors',
    feature: 'Handbag',
    price: '$400',
    byprice: 'under-500',
    dimensions: 'L34cm x H20cm x w12cm',
    sex: 'bag-Women',
    brand: 'Gucci',
    brandvalue: 'brand-Gucci',
    manufacturer: 'Singapore',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Pink',
    colorvalue: 'color-Pink',
    description:
      '- Tote bag; Saffiano leather; 100% leather; Gold-tone hardware;  Handle drop: 5.5"";  Adjustable strap: 15.75""-18.25"";  Interior details: 2 open compartments, center zip compartment, back zip pocket;  Lining: 100% polyester;  Dust bag included;  Imported',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-handle-pink-1-1.jpg',
    pic2: 'images_final/product/bag-handle-pink-1-2.jpg',
    pic3: 'images_final/product/bag-handle-pink-1-3.jpg',
  },
  {
    id: 'hb-2',
    name: 'Adrelin Top',
    feature: 'Handbag',
    price: '$220',
    byprice: 'under-500',
    dimensions: 'L35cm x H40cm x W15cm',
    sex: 'bag-Women',
    brand: 'ALDO',
    brandvalue: 'brand-ALDO',
    manufacturer: 'China',
    material: 'Polyurethane',
    materialvalue: 'mat-Polyurethane',
    color: 'White',
    colorvalue: 'color-White',
    description:
      '- Solid tone textured bag with metallic details; Polyurethane; Slot through fastening; 1 inner zip pocket; 2 inner slot pockets; Lined interior; Single top handle; Adjustable pin buckle shoulder strap; Detachable pom pom keychain',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bags-aldo-Bone-2-1.jpg',
    pic2: 'images_final/product/bags-aldo-Bone-2-2.jpg',
    pic3: 'images_final/product/bags-aldo-Bone-2-3.jpg',
    pic4: 'images_final/product/bags-aldo-Bone-2-4.jpg',
    pic5: 'images_final/product/bags-aldo-Bone-2-5.jpg',
    pic6: 'images_final/product/bags-aldo-Bone-2-6.jpg',
  },
  {
    id: 'hb-3',
    name: 'Chester Street Miri',
    feature: 'Handbag',
    price: '$700',
    byprice: 'under-1000',
    dimensions: 'L21.5cm x H27.5cm x W10.5cm',
    sex: 'bag-Women',
    brand: 'Kate Spade',
    brandvalue: 'brand-KateSpade',
    manufacturer: 'United State',
    material: 'Saffiano',
    materialvalue: 'mat-Saffiano',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '-Saffiano;Two way spade jacquard lining;Satchel with zip closure;Interior zip pocket;Interior slide pocket;NO dust bag,paper bag and box is provided',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-katespade-black-3-1.jpg',
    pic2: 'images_final/product/bag-katespade-black-3-2.jpg',
    pic3: 'images_final/product/bag-katespade-black-3-3.jpg',
  },
  {
    id: 'hb-4',
    name: 'Becky Double',
    feature: 'Handbag',
    price: '$1680',
    byprice: 'under-2000',
    dimensions: 'L19cm x H5cm x W11cm',
    sex: 'bag-Women',
    brand: 'Yves Saint Laurent',
    brandvalue: 'brand-YvesSaintLaurent',
    manufacturer: 'United State',
    material: 'Lambskin',
    materialvalue: 'mat-Lambskin',
    color: 'Black',
    colorvalue: 'color-Black',
    description: '- Main Color : Black; Main Material : 100% Lambskin; Country Of Origin : Italy',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-saint-black-4-1.jpg',
    pic2: 'images_final/product/bag-saint-black-4-2.jpg',
    pic3: 'images_final/product/bag-saint-black-4-3.jpg',
    pic4: 'images_final/product/bag-saint-black-4-4.jpg',
    pic5: 'images_final/product/bag-saint-black-4-5.jpg',
    pic6: 'images_final/product/bag-saint-black-4-6.jpg',
  },
  {
    id: 'hb-5',
    name: 'Marmont Small',
    feature: 'Handbag',
    price: '$1500',
    byprice: 'under-2000',
    dimensions: 'L24cm x H15cm x W7cm',
    sex: 'bag-Women',
    brand: 'Gucci',
    brandvalue: 'brand-Gucci',
    manufacturer: 'Italy',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'White',
    colorvalue: 'color-White',
    description:
      "- Shoulder Strap's Length(cm): 123-133; Closure: Zipper; Interior: Slip Pocket; Main Color : White; Main Material : 100% Calfskin; Country Of Origin : Italy",
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-should-white-5-1.jpg',
    pic2: 'images_final/product/bag-should-white-5-2.jpg',
    pic3: 'images_final/product/bag-should-white-5-3.jpg',
    pic4: 'images_final/product/bag-should-white-5-4.jpg',
    pic5: 'images_final/product/bag-should-white-5-5.jpg',
    pic6: 'images_final/product/bag-should-white-5-6.jpg',
  },
  {
    id: 'hb-6',
    name: 'Becca Status Satchel',
    feature: 'Handbag',
    price: '$416',
    byprice: 'under-500',
    dimensions: 'L31cm x H22cm x W12cm',
    sex: 'bag-Women',
    brand: 'Guess',
    brandvalue: 'brand-Guess',
    manufacturer: 'China',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Solid tone faux leather hand bag with charm detail; Polyurethane; Lined interior; Magnetic closure; 2 open compartments; 2 zippered compartments; 1 inner zip pocket; 3 inner slot pockets; 1 rear zip pocket; Twin handles; Detachable and adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-guess-black-6-1.jpg',
    pic2: 'images_final/product/bag-guess-black-6-2.jpg',
    pic3: 'images_final/product/bag-guess-black-6-3.jpg',
    pic4: 'images_final/product/bag-guess-black-6-4.jpg',
    pic5: 'images_final/product/bag-guess-black-6-5.jpg',
    pic6: 'images_final/product/bag-guess-black-6-6.jpg',
  },
  {
    id: 'hb-7',
    name: 'Mia Grab',
    feature: 'Handbag',
    price: '$200',
    byprice: 'under-500',
    dimensions: 'L25cm x H22cm x W12cm',
    sex: 'bag-Women',
    brand: 'Fiorelli',
    brandvalue: 'brand-Fiorelli',
    manufacturer: 'China',
    material: 'Polyurethane',
    materialvalue: 'mat-Polyurethane',
    color: 'White',
    colorvalue: 'color-White',
    description:
      '‘- Floral-printed faux leather crossbody bag; Polyurethane; Front & rear zip compartments; Front flap pocket; Main compartment with zip fastening; Lined interior; 2 inner slot pockets, 1 zip pocket; Twin grab handles; Adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-miagrab-7-1.jpg',
    pic2: 'images_final/product/bag-miagrab-7-2.jpg',
    pic3: 'images_final/product/bag-miagrab-7-3.jpg',
    pic4: 'images_final/product/bag-miagrab-7-4.jpg',
    pic5: 'images_final/product/bag-miagrab-7-5.jpg',
    pic6: 'images_final/product/bag-miagrab-7-6.jpg',
  },
  {
    id: 'hb-8',
    name: 'Crossbody',
    feature: 'Handbag',
    price: '$1000',
    byprice: 'under-2000',
    dimensions: 'L19.5cm x H15.5cm x W4.5cm',
    sex: 'bag-Women',
    brand: 'Bvlgari',
    brandvalue: 'brand-Bvlgari',
    manufacturer: 'Italy',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'White',
    colorvalue: 'color-White',
    description:
      '‘- Paneled bag with snake motif; Genuine leather; Top flap with slot through closure; 1 inner card slot; Detachable chain strap; Comes with water-resistant cover',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-crossbody-white-8-1.jpg',
    pic2: 'images_final/product/bag-crossbody-white-8-2.jpg',
    pic3: 'images_final/product/bag-crossbody-white-8-3.jpg',
    pic4: 'images_final/product/bag-crossbody-white-8-4.jpg',
    pic5: 'images_final/product/bag-crossbody-white-8-5.jpg',
    pic6: 'images_final/product/bag-crossbody-white-8-6.jpg',
  },
  {
    id: 'hb-9',
    name: 'Lola Shopper',
    feature: 'Handbag',
    price: '$520',
    byprice: 'under-1000',
    dimensions: 'L28cm x H25cm x W14.5cm',
    sex: 'bag-Women',
    brand: 'Guess',
    brandvalue: 'brand-Guess',
    manufacturer: 'Vietnam',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Pink',
    colorvalue: 'color-Pink',
    description:
      '‘- Quilted handbag with emboss detail; Polyurethane; Rear zip pocket; Dual compartment with zip closure; Lined interior; 3 inner slot pockets, 1 zip pocket; Twin grab handles',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-guess-pink-9-1.jpg',
    pic2: 'images_final/product/bag-guess-pink-9-2.jpg',
    pic3: 'images_final/product/bag-guess-pink-9-3.jpg',
    pic4: 'images_final/product/bag-guess-pink-9-4.jpg',
    pic5: 'images_final/product/bag-guess-pink-9-5.jpg',
    pic6: 'images_final/product/bag-guess-pink-9-6.jpg',
  },
  {
    id: 'hb-10',
    name: 'Signature',
    feature: 'Handbag',
    price: '$810',
    byprice: 'under-1000',
    dimensions: 'L26cm x H15.2cm x W7.6cm',
    sex: 'bag-Women',
    brand: 'Coach',
    brandvalue: 'brand-Coach',
    manufacturer: 'Vietnam',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Red',
    colorvalue: 'color-Red',
    description:
      '- Pebbled leather shoulder bag with Tea Rose-engraved metal corners; Leather; Snap closure; 1 back slip pocket; 2 main compartments; 1 centre zip pocket; 1 inner slip pocket; Lined interior; Detachable top handle; Adjustable and detachable shoulder strap\n',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/bag-Shoudler-Red-10-1.jpg',
    pic2: 'images_final/product/bag-Shoudler-Red-10-2.jpg',
    pic3: 'images_final/product/bag-Shoudler-Red-10-3.jpg',
    pic4: 'images_final/product/bag-Shoudler-Red-10-4.jpg',
    pic5: 'images_final/product/bag-Shoudler-Red-10-5.jpg',
    pic6: 'images_final/product/bag-Shoudler-Red-10-6.jpg',
  },
  {
    id: 'sb-1',
    name: 'Heritage Crossbody',
    feature: 'Slingbag',
    price: '$30',
    byprice: 'under-100',
    dimensions: 'L13cm x H18cm x W3cm',
    sex: 'bag-Men',
    brand: 'Nike',
    brandvalue: 'brand-Nike',
    manufacturer: 'Malaysia',
    material: 'Nylon',
    materialvalue: 'mat-Nylon',
    color: 'Red',
    colorvalue: 'color-Red',
    description:
      '- Best for lifestyle\n- Solid shade sling bag with logo print\n- Nylon blend\n- Front & rear slot pockets\n- Main compartment with zip closure\n- Adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-nike-1-1.jpg',
    pic2: 'images_final/product/slingbag-nike-1-2.jpg',
    pic3: 'images_final/product/slingbag-nike-1-3.jpg',
    pic4: 'images_final/product/slingbag-nike-1-4.jpg',
    pic5: 'images_final/product/slingbag-nike-1-5.jpg',
    pic6: 'images_final/product/slingbag-nike-1-6.jpg',
  },
  {
    id: 'sb-2',
    name: 'Originals sprt festival',
    feature: 'Slingbag',
    price: '$45',
    byprice: 'under-100',
    dimensions: 'L12cm x H17cm x W2.5cm',
    sex: 'bag-Men',
    brand: 'Adidas',
    brandvalue: 'brand-Adidas',
    manufacturer: 'Vietnam',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Adidas originals\n- Best for lifestyle\n- Monochrome trefoil logo sling bag\n- PFC-free water-repellent finish\n- Polyester\n- Zip fastening\n- One front zip pocket\n- Detachable adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-adidas-2-1.jpg',
    pic2: 'images_final/product/slingbag-adidas-2-2.jpg',
    pic3: 'images_final/product/slingbag-adidas-2-3.jpg',
    pic4: 'images_final/product/slingbag-adidas-2-4.jpg',
    pic5: 'images_final/product/slingbag-adidas-2-5.jpg',
    pic6: 'images_final/product/slingbag-adidas-2-6.jpg',
  },
  {
    id: 'sb-3',
    name: 'Japan Range Vertical',
    feature: 'Slingbag',
    price: '$50',
    byprice: 'under-100',
    dimensions: 'L18cm x H24cm x W6cm',
    sex: 'bag-Men',
    brand: 'Champion',
    brandvalue: 'brand-Champion',
    manufacturer: 'Singapore',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Embroidered brand print sling bag\n- Canvas\n- Zip fastening\n- Unlined interior\n- 1 exterior front zip pocket\n- 1 interior slot pocket\n- Adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-champion-3-1.jpg',
    pic2: 'images_final/product/slingbag-champion-3-2.jpg',
    pic3: 'images_final/product/slingbag-champion-3-3.jpg',
    pic4: 'images_final/product/slingbag-champion-3-4.jpg',
    pic5: 'images_final/product/slingbag-champion-3-5.jpg',
  },
  {
    id: 'sb-4',
    name: 'Classic Organizer',
    feature: 'Slingbag',
    price: '$30',
    byprice: 'under-100',
    dimensions: 'L12.5cm x H18.5cm x W3cm',
    sex: 'bag-Men',
    brand: 'Adidas',
    brandvalue: 'brand-Adidas',
    manufacturer: 'Indonesia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Adidas performance\n- Best for training\n- Solid toned small sling bag\n- Recycled polyester\n- Zip fastening with buckle closure\n- 1 exterior pocket\n- 1 interior slot\n- Detachable and adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-adidas-4-1.jpg',
    pic2: 'images_final/product/slingbag-adidas-4-2.jpg',
    pic3: 'images_final/product/slingbag-adidas-4-3.jpg',
    pic4: 'images_final/product/slingbag-adidas-4-4.jpg',
    pic5: 'images_final/product/slingbag-adidas-4-5.jpg',
    pic6: 'images_final/product/slingbag-adidas-4-6.jpg',
  },
  {
    id: 'sb-5',
    name: 'UA Crossbody',
    feature: 'Slingbag',
    price: '$110',
    byprice: 'under-500',
    dimensions: 'L15cm x H23cm x W8cm',
    sex: 'bag-Men',
    brand: 'Under Armour',
    brandvalue: 'brand-UnderArmour',
    manufacturer: 'Vietnam',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Best for training\n- Brand logo print crossbody bag\n- Polyester\n- Zip fastening\n- 2 exterior pockets\n- Adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-ua-5-1.jpg',
    pic2: 'images_final/product/slingbag-ua-5-2.jpg',
    pic3: 'images_final/product/slingbag-ua-5-3.jpg',
    pic4: 'images_final/product/slingbag-ua-5-4.jpg',
    pic5: 'images_final/product/slingbag-ua-5-5.jpg',
  },
  {
    id: 'sb-6',
    name: 'Canvas Green',
    feature: 'Slingbag',
    price: '$210',
    byprice: 'under-500',
    dimensions: 'L13cm x H18cm x W3cm',
    sex: 'bag-Men',
    brand: 'Oxhide',
    brandvalue: 'brand-Oxhide',
    manufacturer: 'Malaysia',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Green',
    colorvalue: 'color-Green',
    description:
      "-This casual men's bag is made of high density canvas and full grain cow leather.\n-Bag has a beautiful combination of Dark Green(canvas) and Black (leather) colour.\n-It can be carried as a sling bag or as a crossbody. \n-It is very Light weight.",
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-ox-6-1.jpg',
    pic2: 'images_final/product/slingbag-ox-6-2.jpg',
    pic3: 'images_final/product/slingbag-ox-6-3.jpg',
    pic4: 'images_final/product/slingbag-ox-6-4.jpg',
    pic5: 'images_final/product/slingbag-ox-6-5.jpg',
  },
  {
    id: 'sb-7',
    name: 'Faux Leather',
    feature: 'Slingbag',
    price: '$140',
    byprice: 'under-500',
    dimensions: 'L31.5cm x H24cm x W7.5cm',
    sex: 'bag-Men',
    brand: 'Playboy',
    brandvalue: 'brand-Playboy',
    manufacturer: 'Singapore',
    material: 'Leather',
    materialvalue: 'mat-Leather',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Printed sling bag\n- Polyurethane\n- 2 exterior front pockets\n- 1 exterior back slot\n- Zip fastening with magnetic closure\n- 1 interior pocket\n- 2 interior slots\n- Adjustable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-pl-7-1.jpg',
    pic2: 'images_final/product/slingbag-pl-7-2.jpg',
    pic3: 'images_final/product/slingbag-pl-7-3.jpg',
    pic4: 'images_final/product/slingbag-pl-7-4.jpg',
    pic5: 'images_final/product/slingbag-pl-7-5.jpg',
    pic6: 'images_final/product/slingbag-pl-7-6.jpg',
  },
  {
    id: 'sb-8',
    name: 'Women Core Up',
    feature: 'Slingbag',
    price: '$40',
    byprice: 'under-100',
    dimensions: 'L20.5cm x H12cm x W1.8cm',
    sex: 'bag-Women',
    brand: 'Puma',
    brandvalue: 'brand-Puma',
    manufacturer: 'Malaysia',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Pink',
    colorvalue: 'color-Pink',
    description:
      '- Best for lifestyle\n- Logo print mini sling bag\n- Polyester and polyurethane\n- Zip fastening\n- Lined interior\n- 1 inner slip pocket\n- Adjustable and detachable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-pm-8-1.jpg',
    pic2: 'images_final/product/slingbag-pm-8-2.jpg',
    pic3: 'images_final/product/slingbag-pm-8-3.jpg',
    pic4: 'images_final/product/slingbag-pm-8-4.jpg',
    pic5: 'images_final/product/slingbag-pm-8-5.jpg',
    pic6: 'images_final/product/slingbag-pm-8-6.jpg',
  },
  {
    id: 'sb-9',
    name: 'Abanu M Crossbody',
    feature: 'Slingbag',
    price: '$220',
    byprice: 'under-500',
    dimensions: 'L23cm x H16cm x W5cm',
    sex: 'bag-Women',
    brand: 'Kipling',
    brandvalue: 'brand-Kipling',
    manufacturer: 'Vietnam',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Grey',
    colorvalue: 'color-Grey',
    description:
      '- Embossed brand patch crossbody bag with multiple compartments\n- Polyamide\n- Twin compartments with zip fastening\n- One front zip pocket\n- One inner slot pocket\n- One inner zip pocket\n- One back zip pocket\n- Adjustable shoulder strap\n- Comes with iconic monkey keychain',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-kp-9-1.jpg',
    pic2: 'images_final/product/slingbag-kp-9-2.jpg',
    pic3: 'images_final/product/slingbag-kp-9-3.jpg',
    pic4: 'images_final/product/slingbag-kp-9-4.jpg',
    pic5: 'images_final/product/slingbag-kp-9-5.jpg',
    pic6: 'images_final/product/slingbag-kp-9-6.jpg',
  },
  {
    id: 'sb-10',
    name: 'Originals X-Bag',
    feature: 'Slingbag',
    price: '$310',
    byprice: 'under-500',
    dimensions: 'L17cm x H29cm x W4cm',
    sex: 'bag-Women',
    brand: 'Puma',
    brandvalue: 'brand-Puma',
    manufacturer: 'Myanmar',
    material: 'Polyester',
    materialvalue: 'mat-Polyester',
    color: 'Black',
    colorvalue: 'color-Black',
    description:
      '- Best for lifestyle\n- Metallic logo print crossbody bag\n- Polyester\n- Zippered main compartment\n- 1 front zip pocket\n- Lined interior\n- 3 inner card slots\n- 1 inner zip mesh pocket\n- 1 inner sleeve pocket\n- Adjustable and detachable shoulder strap',
    guarantee:
      'Not 100% satisfied with your item? We offer 30 days free returns (7 days for Pre-Loved items), no questions asked.\nPack your item (with its original packaging and tags intact) together with the returns slip (Seller only) into your ZALORA delivery package. Then simply nearest PosLaju or CollectCo centre (Malaysia) or arrange pick up with Authorised Business Partner of SF Express: Jifee Technologies.\nFor more information, check out our FAQ.',
    pic1: 'images_final/product/slingbag-pm-10-1.jpg',
    pic2: 'images_final/product/slingbag-pm-10-2.jpg',
    pic3: 'images_final/product/slingbag-pm-10-3.jpg',
    pic4: 'images_final/product/slingbag-pm-10-4.jpg',
    pic5: 'images_final/product/slingbag-pm-10-5.jpg',
    pic6: 'images_final/product/slingbag-pm-10-6.jpg',
  },
];
